# Generated by Django 5.1.4 on 2025-04-04 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [("can_view_statistic", "can_view_statistic")],
                "verbose_name": "Пользоатель",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
