# Generated by Django 5.1.4 on 2025-04-04 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [("can_view_statistic", "can view statistic")],
                "verbose_name": "Пользоатель",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
