# Generated by Django 5.1.4 on 2025-04-04 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("can_view_statistic", "can view statistic"),
                    ("can_send_mail", "can sand mail"),
                    ("manager", "manager"),
                ],
                "verbose_name": "Пользоатель",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
