# Generated by Django 5.1.4 on 2025-04-11 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [("can_send_mail", "can sand mail")],
                "verbose_name": "Пользоатель",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
