# Generated by Django 5.1.4 on 2024-12-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MailingRecipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "email",
                    models.EmailField(
                        help_text="email получателя рассылки",
                        max_length=254,
                        unique=True,
                        verbose_name="email получателя рассылки",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(help_text="Ф.И.О. получателя", max_length=150, verbose_name="Ф.И.О. получателя"),
                ),
                (
                    "commentary",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий о получателе рассылки"),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
                "ordering": ["full_name"],
            },
        ),
    ]
