# Generated by Django 5.1.4 on 2024-12-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject", models.CharField(help_text="Тема", max_length=150, verbose_name="Тема сообщения")),
                ("message", models.TextField(help_text="Тескт сообщения", verbose_name="Тескт сообщения")),
            ],
        ),
    ]
