# Generated by Django 5.1.4 on 2024-12-19 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mailing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_date", models.DateTimeField(verbose_name="Дата и время первой рассылки")),
                ("end_date", models.DateTimeField(verbose_name="Дата и время окончания рассылки")),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("Создана", "Создана"), ("Запущена", "Запущена"), ("Завершена", "Завершена")],
                        default="Создана",
                        max_length=9,
                        null=True,
                        verbose_name="Статус рассылки",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mailings",
                        to="mailing.message",
                        verbose_name="сообщение",
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        related_name="recipients", to="mailing.mailingrecipient", verbose_name="Получатели рассылки"
                    ),
                ),
            ],
        ),
    ]
