# Generated by Django 5.1.4 on 2024-12-24 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_mailing"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={"ordering": ["status"], "verbose_name": "Рассылка", "verbose_name_plural": "Рассылки"},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["subject"], "verbose_name": "Сообщение", "verbose_name_plural": "Сообщения"},
        ),
    ]
