# Generated by Django 5.1.4 on 2025-04-01 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0004_mailingrecipient_author_message_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="author",
        ),
    ]
