# Generated by Django 5.1.4 on 2024-12-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0004_alter_mailing_options_alter_message_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingrecipient",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="email получателя рассылки"),
        ),
        migrations.AlterField(
            model_name="mailingrecipient",
            name="full_name",
            field=models.CharField(max_length=150, verbose_name="Ф.И.О. получателя"),
        ),
        migrations.AlterField(
            model_name="message",
            name="message",
            field=models.TextField(verbose_name="Тескт сообщения"),
        ),
        migrations.AlterField(
            model_name="message",
            name="subject",
            field=models.CharField(max_length=150, verbose_name="Тема сообщения"),
        ),
    ]
