# Generated by Django 5.1.4 on 2025-04-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0005_remove_message_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingrecipient",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="email получателя рассылки"),
        ),
    ]
