# Generated by Django 5.1.4 on 2025-03-17 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0005_alter_mailingrecipient_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailingAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_attempt", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время попытки")),
                (
                    "status",
                    models.CharField(
                        choices=[("Успешно", "Успешно"), ("Не успешно", "Не успешно")],
                        verbose_name="Успешность отправки",
                    ),
                ),
                ("server_response", models.TextField(verbose_name="Ответ почтового сервера")),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempt",
                        to="mailing.mailing",
                        verbose_name="рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылки",
            },
        ),
    ]
