# Generated by Django 5.1.4 on 2025-04-11 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0006_alter_mailingrecipient_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["status"],
                "permissions": [("can_view_statistic", "can view statistic"), ("manager", "manager")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="mailingrecipient",
            options={
                "ordering": ["full_name"],
                "permissions": [("manager", "manager")],
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["subject"],
                "permissions": [("manager", "manager")],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
    ]
