# Generated by Django 5.1.4 on 2025-04-11 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0007_alter_mailing_options_alter_mailingrecipient_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["status"],
                "permissions": [
                    ("can_view_statistic", "can view statistic"),
                    ("can_view_all_mailing", "can view all mailing"),
                    ("can_block_mailing", "can block mailing"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="mailingrecipient",
            options={
                "ordering": ["full_name"],
                "permissions": [("can_view_all_client", "can view all client")],
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["subject"], "verbose_name": "Сообщение", "verbose_name_plural": "Сообщения"},
        ),
    ]
