# Generated by Django 5.1.4 on 2025-04-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0008_alter_mailing_options_alter_mailingrecipient_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["status"],
                "permissions": [
                    ("can_view_statistic", "can view statistic"),
                    ("can_block_mailing", "can block mailing"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterField(
            model_name="mailing",
            name="start_date",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="Дата и время первой рассылки"
            ),
        ),
    ]
