# Generated by Django 5.1.4 on 2025-04-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0009_alter_mailing_options_alter_mailing_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="recipients",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="recipients",
                to="mailing.mailingrecipient",
                verbose_name="Получатели рассылки",
            ),
        ),
    ]
